name: Conditional SQL Script Review

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/sql_scripts/**'

jobs:

  check_sql_content:
    runs-on: ubuntu-latest
    outputs:
      requires_review: ${{ steps.check_content.outputs.needs_review }}
    steps:
    - uses: actions/checkout@v2
    - name: Check SQL Content
      id: check_content
      run: |
        # Check if the PR contains CREATE statements
        CREATE_STATEMENT_COUNT=$(git diff origin/${{ github.base_ref }} HEAD -- '.github/sql_scripts/' | grep -c 'CREATE')
        
        if [ $CREATE_STATEMENT_COUNT -gt 0 ]; then
          echo "needs_review=true" >> $GITHUB_OUTPUT
        else
          echo "needs_review=false" >> $GITHUB_OUTPUT
        fi

  require_reviewers:
    needs: check_sql_content
    if: needs.check_sql_content.outputs.requires_review == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Request Reviews
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.pulls.requestReviewers({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            reviewers: ['Notyou1231'] # Replace with actual GitHub usernames
          })
