name: Conditional Review Enforcement

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/sql_script/**'

permissions:
  contents: read
  pull-requests: write  # Needed for assigning reviewers

jobs:
  review_sql_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect CREATE statements in SQL files
        id: detect_create_statements
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '\.github/sql_script/.*\.(sql|txt)$' || true)
          echo "Changed SQL files: $CHANGED_FILES"

          CREATE_STATEMENT_FOUND=false
          if [ -n "$CHANGED_FILES" ]; then
            for file in $CHANGED_FILES; do
              SQL_CONTENT=$(sed -E '/^\s*--/d' "$file" | sed -E ':a;N;$!ba;s/\s*\/\*.*?\*\///g')
              if echo "$SQL_CONTENT" | grep -iq "CREATE"; then
                CREATE_STATEMENT_FOUND=true
                echo "CREATE statement found in $file"
                break
              fi
            done
          fi

          echo "create_script=${CREATE_STATEMENT_FOUND}" >> $GITHUB_ENV

      - name: Add reviewer if CREATE statements found
        if: env.create_script == 'true'
        run: |
          echo "Assigning reviewer for PR #${{ github.event.pull_request.number }}"
          gh pr edit ${{ github.event.pull_request.number }} --add-reviewer Notyou1231
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve check
        id: approve_check
        run: |
          if [ "${{ env.create_script }}" = "true" ]; then
            echo "Reviewer approval required."
            exit 1  # Fail if CREATE statement is found and approval hasn't occurred
          else
            echo "No approval required."
            exit 0  # Pass if no CREATE statement
          fi
