name: Review and Approve/Merge SQL Scripts

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/sql_script/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  process_sql_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Check SQL files for CREATE statements
        id: check_sql_changes
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '\.github/sql_script/.*\.(sql|txt)$' || true)
          echo "Changed SQL files: $CHANGED_FILES"

          CREATE_STATEMENT_FOUND=false
          if [ -n "$CHANGED_FILES" ]; then
            for file in $CHANGED_FILES; do
              if [ -f "$file" ]; then
                SQL_CONTENT=$(sed -E '/^\s*--/d' "$file" | sed -E ':a;N;$!ba;s/\s*\/\*.*?\*\///g')
                if echo "$SQL_CONTENT" | grep -iq "CREATE"; then
                  CREATE_STATEMENT_FOUND=true
                  echo "CREATE statement found in $file"
                  break
                fi
              fi
            done
          fi

          if [ "$CREATE_STATEMENT_FOUND" = true ]; then
            echo "create_script=true" >> "$GITHUB_ENV"
          else
            echo "create_script=false" >> "$GITHUB_ENV"
          fi

      - name: Assign reviewer for CREATE scripts
        if: env.create_script == 'true'
        run: |
          echo "✅ CREATE statement detected. Assigning reviewer: sumeshmg"
          gh pr edit ${{ github.event.pull_request.number }} --add-reviewer Notyou1231 --add-reviewer sumeshmg || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-approve PR if no CREATE statement
        if: env.create_script == 'false'
        run: |
          echo "ℹ️ No CREATE statement found. Auto-approving PR."
          gh pr review ${{ github.event.pull_request.number }} --approve --body "✅ Auto-approved as no CREATE statements detected."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify if reviewer was assigned
        if: env.create_script == 'true'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "⚠️ Manual review required. Reviewer `Notyou1231` has been assigned."
        env:
          GH_TOKEN: ${{ secrets.PA_TOKEN }}

      - name: Notify if auto-approved
        if: env.create_script == 'false'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "✅ PR auto-approved as no CREATE statements were found."
        env:
          GH_TOKEN: ${{ secrets.PA_TOKEN }}

      - name: Notify via AWS SNS
        if: env.create_script == 'true'
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '\.github/sql_script/.*\.(sql|txt)$' || true)
          
          MESSAGE=$(cat <<EOF
{
  "Subject": "Manual Review Required for SQL Script Changes",
  "Message": "<h3>Pull Request #${{ github.event.pull_request.number }} requires manual review.</h3>
  <p><strong>PR Link:</strong> <a href=\\"${{ github.event.pull_request.html_url }}\\">View PR</a></p>
  
  <p><strong>Changed Files:</strong></p>
  <ul>
    $(for file in $CHANGED_FILES; do echo "<li>$file</li>"; done)
  </ul>
  
  <div style=\\"margin-top: 20px;\\">
    <a href=\\"https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}/approve\\" style=\\"padding: 10px 20px; background-color: green; color: white; text-decoration: none; border-radius: 5px;\\">Approve</a>
    <a href=\\"https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}/reject\\" style=\\"padding: 10px 20px; background-color: red; color: white; text-decoration: none; border-radius: 5px; margin-left: 10px;\\">Reject</a>
  </div>
  <br>
  <p>If you wish to stop receiving notifications from this topic, you can unsubscribe by clicking <a href=\\"https://sns.***.amazonaws.com/unsubscribe.html?SubscriptionArn=arn:aws:sns:***:767397784856:ReviewNotifications:36e5d695-9f93-476f-9a87-c3c8f72592c7&Endpoint=sumeshmgwork@gmail.com\\">here</a>.</p>"
}
EOF
)

          echo "$MESSAGE" | aws sns publish --cli-input-json file:///dev/stdin --region "${{ secrets.AWS_REGION }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
