name: Add Reviewers for CREATE Statements

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Detect CREATE Statements
      id: check_create
      run: |
        CHANGED_FILES=$(git diff --name-only origin/main | grep -E '\.sql$' || true)
        echo "Changed SQL files: $CHANGED_FILES"

        for file in $CHANGED_FILES; do
          if grep -qi 'create' "$file"; then
            echo "CREATE statement found in $file"
            echo "create_found=true" >> $GITHUB_ENV
          fi
        done

    - name: Add Reviewers
      if: env.create_found == 'true'
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"reviewers":["Notyou1231"]}' \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/requested_reviewers"
