name: Execute SQL Scripts and Assign Reviewer

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/sql_script/**'

jobs:
  execute_sql_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # To get the previous 2 commits

      - name: Use Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-connector-python

      - name: Check for SQL script changes and assign reviewer
        id: check_sql_changes
        run: |
          # Get list of changed files in the pull request
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.github/sql_script/.*\.(sql|txt)$' || true)
          
          # Check if changed files are not empty
          if [ ! -z "$CHANGED_FILES" ]; then
            for file in $CHANGED_FILES; do
              if [ -f "$file" ]; then
                # Read the content of the file and check for 'CREATE' statement
                CONTENT=$(cat "$file")
                if echo "$CONTENT" | grep -iq "CREATE"; then
                  echo "create_script=true" >> $GITHUB_ENV
                else
                  echo "create_script=false" >> $GITHUB_ENV
                fi
              fi
            done
          else
            echo "No SQL files were changed in this pull request"
            echo "create_script=false" >> $GITHUB_ENV
          fi

      - name: Assign reviewer if CREATE statement is found
        if: env.create_script == 'true'
        uses: kentaro-m/auto-assign-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: 'Notyou1231'

      - name: Execute SQL Scripts
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.github/sql_script/.*\.(sql|txt)$' || true)
          
          if [ ! -z "$CHANGED_FILES" ]; then
            for file in $CHANGED_FILES; do
              if [ -f "$file" ]; then
                echo "Processing changed file: $file"
                python .github/scripts/execute_snowflake_script.py "$file"
              fi
            done
          else
            echo "No SQL files were changed in this push"
          fi
