name: Add Reviewers for CREATE Statements

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch full history to ensure access to main branch

    - name: Fetch Main Branch
      run: |
        git fetch origin main # Fetch main branch explicitly

    - name: Detect CREATE Statements
      id: check_create
      run: |
        # Identify changed SQL files
        CHANGED_FILES=$(git diff --name-only origin/main | grep -E '\.sql$' || true)
        echo "Changed SQL files: $CHANGED_FILES"

        # Check for CREATE statements
        create_found=false
        for file in $CHANGED_FILES; do
          if grep -qi 'create' "$file"; then
            echo "CREATE statement found in $file"
            create_found=true
            break
          fi
        done

        echo "create_found=$create_found" >> $GITHUB_ENV

    - name: Add Reviewers
      if: env.create_found == 'true'
      uses: peter-evans/add-reviewers@v3
      with:
        reviewers: |
          Notyou1231
