name: Add Reviewers on PR with CREATE Statements

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for CREATE statements in changed SQL files
        id: check-create
        run: |
          CHANGED_FILES=$(git diff --name-only origin/main | grep -E '\.sql$' || true)
          echo "Changed SQL files: $CHANGED_FILES"
          for file in $CHANGED_FILES; do
            if grep -qi 'create' "$file"; then
              echo "CREATE statement found in $file"
              echo "create_found=true" >> $GITHUB_ENV
              break
            fi
          done

      - name: Add reviewers
        if: env.create_found == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            -d '{"reviewers":["reviewer_username1","reviewer_username2"]}'
