name: Auto-approve PR for Specific Paths

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/sql_script/**'  # Trigger when files in this path are changed

jobs:
  approve_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Approve PR using GitHub API as Code Owner
        env:
          GH_TOKEN: ${{ secrets.HK_PA_TOKEN }}  # PAT for 'Notyou1231'
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number < $GITHUB_EVENT_PATH)
          REPO_NAME=$(jq --raw-output .repository.full_name < $GITHUB_EVENT_PATH)

          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -d '{"event":"APPROVE","body":"Auto-approving this PR by Code Owner"}' \
            "https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER/reviews"
