name: Review SQL Scripts

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/sql_script/**'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for accurate diffing

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Debug PR Information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Base Branch: ${{ github.base_ref }}"
          echo "Head Branch: ${{ github.head_ref }}"
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
          echo "Pull Request Number: ${{ github.event.pull_request.number }}"

      - name: Check for CREATE statements in SQL scripts
        id: check_sql_changes
        run: |
          # Use explicit base and head SHAs for diffing
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '\.github/sql_script/.*\.(sql|txt)$' || true)
          
          echo "Changed SQL files: $CHANGED_FILES"
          
          if [ -n "$CHANGED_FILES" ]; then
            CREATE_SCRIPT_FOUND=false
            
            for file in $CHANGED_FILES; do
              if [ -f "$file" ]; then
                # Check for 'CREATE' statement
                if grep -iq "CREATE" "$file"; then
                  CREATE_SCRIPT_FOUND=true
                  echo "CREATE statement found in $file"
                  break
                fi
              fi
            done
            
            if [ "$CREATE_SCRIPT_FOUND" = true ]; then
              echo "create_script=true" >> "$GITHUB_ENV"
            else
              echo "create_script=false" >> "$GITHUB_ENV"
            fi
          else
            echo "No SQL files were changed in this pull request"
            echo "create_script=false" >> "$GITHUB_ENV"
          fi

      - name: Assign reviewer
        if: env.create_script == 'true'
        run: |
          echo "Assigning reviewer for CREATE scripts..."
          # Assign reviewer using GitHub CLI
          gh pr edit ${{ github.event.pull_request.number }} --add-reviewer Notyou1231 || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify if no reviewer is needed
        if: env.create_script != 'true'
        run: |
          echo "No CREATE statement found. No reviewer will be assigned."
