name: Review SQL Scripts

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/sql_script/**'

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review_sql_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for accurate diffing

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Check for CREATE statements in SQL files
        id: check_sql_changes
        run: |
          # Use explicit base and head SHAs for diffing
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '\.github/sql_script/.*\.(sql|txt)$' || true)

          echo "Changed SQL files: $CHANGED_FILES"
          
          if [ -n "$CHANGED_FILES" ]; then
            CREATE_STATEMENT_FOUND=false
            
            for file in $CHANGED_FILES; do
              if [ -f "$file" ]; then
                echo "Analyzing file: $file"

                # Remove comments and check for CREATE statements
                SQL_CONTENT=$(grep -vE '^\s*(--|/\*|.*\*/)' "$file")
                if echo "$SQL_CONTENT" | grep -iq "CREATE"; then
                  CREATE_STATEMENT_FOUND=true
                  echo "CREATE statement found in $file"
                  break
                fi
              fi
            done
            
            if [ "$CREATE_STATEMENT_FOUND" = true ]; then
              echo "create_script=true" >> "$GITHUB_ENV"
            else
              echo "create_script=false" >> "$GITHUB_ENV"
            fi
          else
            echo "No SQL files were changed in this pull request"
            echo "create_script=false" >> "$GITHUB_ENV"

      - name: Log message
        run: |
          if [ "$create_script" = "true" ]; then
            echo "CREATE statement detected. Reviewer required: Notyou1231"
          else
            echo "No CREATE statement found. No reviewer required."
