name: Run Python Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Check out the code from the repo

      - name: Set up Python
        uses: actions/setup-python@v5  # Set up Python environment
        with:
          python-version: '3.x'  # Specify Python version

      - name: Install dependencies (if any)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies listed in requirements.txt (if present)

      - name: Run the Python script
        run: |
          python .github/utils/generate_jwt.py  # Run the Python script from your repo
